#1.接收客户端 request，并将 request 中带的 header 写入 response header
#2.读取当前系统的环境变量中的 VERSION 配置，并写入 response header
#3.Server 端记录访问日志包括客户端 IP，HTTP 返回码，输出到 server 端的标准输出
#4.当访问 localhost/healthz 时，应返回200

#提交链接🔗：https://jinshuju.net/f/PlZ3xg
#截止时间：10月7日晚23:59前


#接口:
#healthz
#GetRequestParams
#GetEnvironmentVariable
#日志输出（IP、HTTP、返回码）-->server
